version: "3.4"

services:
  common_api:
    container_name: common_api
    hostname: common_api
    build: 
      context: ./common_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./common_api/app:/app
    ports:
      - 9010:9010
    networks:
      - the_network
      - network_api
    stdin_open: true

  minio_api:
    container_name: minio_api
    hostname: minio_api
    build: 
      context: ./minio_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./minio_api/app:/app
    ports: 
      - 9010
    networks:
      - network_api
    stdin_open: true
    
  qrcode_api:
    container_name: qrcode_api
    hostname: qrcode_api
    build: 
      context: ./qrcode_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./qrcode_api/app:/app
    ports: 
      - 9010
    networks:
      - network_api
    stdin_open: true

  # email_api:
  # container_name: email_api
  # hostname: email_api
  # build: 
  #   context: ./email_api
  #   dockerfile: Dockerfile_dev
  # volumes: 
  #   - ./email_api/app:/app
  # ports: 
  #   - 9010
  # networks:
  #   - network_api
  # stdin_open: true


networks: 
  the_network:
    external: true
  
  network_api:
    external: true
  


      # voir pour metttre un nouveau nom de reseau et c'est sur ce nouveau réseau que les api taperont