version: "3.4"

services:
  common_api:
    container_name: common_api
    hostname: common_api
    restart: always
    build: 
      context: ./common_api
      dockerfile: Dockerfile
    volumes: 
      - ./common_api/app:/app
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt
    ports:
      - 9010:9010
    networks:
      - the_network
      - network_api

  # common_api:
  #   container_name: common_api
  #   hostname: common_api
  #   build: 
  #     context: ./common_api
  #     dockerfile: Dockerfile_dev
  #   volumes: 
  #     - ./common_api/app:/app
  #     - cert-handler_certbot-letsencrypt:/etc/letsencrypt
  #   ports:
  #     - 9010:9010
  #   networks:
  #     - the_network
  #     - network_api
  #   stdin_open: true

  minio_api:
    container_name: minio_api
    hostname: minio_api
    build: 
      context: ./minio_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./minio_api/app:/app
    ports: 
      - 9010
    networks:
      - network_api
    stdin_open: true
    
  email_api:
    container_name: email_api
    hostname: email_api
    build: 
      context: ./email_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./email_api/app:/app
    ports: 
      - 9010
    networks:
      - network_api
    stdin_open: true
    
  mongo_api:
    container_name: mongo_api
    hostname: mongo_api
    build: 
      context: ./mongo_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./mongo_api/app:/app
    ports: 
      - 9010
    networks:
      - the_network
    stdin_open: true

  mqtt_api:
    container_name: mqtt_api
    hostname: mqtt_api
    build: 
      context: ./mqtt_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./mqtt_api/app:/app
    ports: 
      - 9010
    networks:
      - the_network
    stdin_open: true

  postgre_api:
    container_name: postgre_api
    hostname: postgre_api
    build: 
      context: ./postgre_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./postgre_api/app:/app
    ports: 
      - 9010
    networks:
      - network_api
    stdin_open: true

volumes: 
  cert-handler_certbot-letsencrypt:
    external: true

networks: 
  the_network:
    external: true
  network_api:
    external: true
      # voir pour metttre un nouveau nom de reseau et c'est sur ce nouveau réseau que les api taperont